//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySach
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAnBan
    {
        public int IDAnBan { get; set; }
        public Nullable<int> IDSach { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> IDPhieuMuon { get; set; }
        public Nullable<int> IDPhieuTra { get; set; }
    
        public virtual tblDauSach tblDauSach { get; set; }
        public virtual tblPhieuMuon tblPhieuMuon { get; set; }
        public virtual tblPhieuTra tblPhieuTra { get; set; }
    }
}
