//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySach
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDauSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDauSach()
        {
            this.tblAnBans = new HashSet<tblAnBan>();
        }
    
        public int IDSach { get; set; }
        public string TenSach { get; set; }
        public string TenTacGia { get; set; }
        public string TheLoaiSach { get; set; }
        public string NgonNgu { get; set; }
        public Nullable<int> Gia { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> SoLuongConLai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAnBan> tblAnBans { get; set; }
    }
}
